project: bpd

spark: "spark"
dask: "dask"
pandas: "pandas"
dask_endpoint: ""

default_backend: "dask"

gdrive:
  diabetes:     "gdrive://1SMf1o0X0y09sLsnLCMMsVSqiZB2kiOk8" 
  google_mini:  "gdrive://1y4gwaS7LjYUhwTex1-lNHJJ71nLEh3fE"