name: BPD Docker Image

on:
  push:
    branches: ["dev", "master", "feat/actions"]

  pull_request:
    branches: ["dev", "master"]

jobs:
  sandbox:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: make build_dockers
    - name: Publish package
      run : pip install twine && twine upload dist/*.whl --skip-existing -u __token__ -p ${{ secrets.PYPI }} 